name: msi_feature_extraction
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - tqdm
  - pip:
    - kdepy
